[app]
name = 'star-mall'
port = 8080
env = 'dev'
debug = true
varsion = 'v0.1'
sessionon = true
sessiongcmaxlifetime = 3600
session_name = 'star-mall'

[database]
[database.mysql]
master_host = 'host'
master_port = 13306
user = 'dg'
password = '123456'
db_name = 'shop'
max_open_conns = 100
max_idle_conns = 20
timeout = 10

[[database.mysql.slaves]]
host = 'host'
port = 23306

[[database.mysql.slaves]]
host = 'host'
port = 33306

[database.redis]
master_host = 'host'
master_port = 16379
password = '123456'

[[database.redis.slaves]]
host = 'host'
port = 26379

[[database.redis.slaves]]
host = 'host'
port = 36379

[mail]
user = "username@qq.com"
SMTP-code = "fsjrvxgzxyoqddhf"
host = "smtp.qq.com"
port = 465
from = "username@qq.com"

[cookie]
name = "star-mall"
domain = "StarMall.com"
path = "/"
maxAge = 3600
secure = false
httpOnly = true
sameSite = "Strict"

[log]
version = "v0.1"
level = "dev"
path = "/var/log/star-Mall/"
max_size = 100
max_backup = 5
max_age = 30
compress = false

[etcd]
endpoints = ["host1:2379", "host2:2379", "host3:2379"]
dial_timeout = "5s"
auto_sync_interval = "5m"
max_call_send_msg_size = 52428800
max_call_recv_msg_size = 52428800
enable_tls = false

[tls]
[tls.server]
cert_file = "/var/certs/server.crt"
key_file = "/var/certs/server.key"
# 认证策略枚举值
# 0: 不要求客户端提供证书，完全忽略客户端身份验证。
# 1: 请求客户端提供证书，但即使未提供或验证失败，仍会继续建立连接。
# 2: 强制要求客户端提供证书，但不验证证书的合法性（如签名是否有效）
# 3: 如果客户端提供了证书，则严格验证证书有效性；未提供则允许连接。
client_auth = 0
min_version = "TLSv1.2"
#pfx_file = "/var/certs/server.pfx"
#pfx_password = "123456"

[tls.client]
ca_cert_file = "/var/certs/server.crt"

[tls.cipher_suites]
suites = ["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"]

[tls.advanced]
session_tickets = true
curve_preferences = ["X25519", "P256"]

[oss]
[oos.TencentCOS]
bucket = "yourBucketName"
region = "your oss region"
secret_id = "your secret id"
secret_key = "your secret key"

[oss.AliCloudOOS]
bucket = "yourBucketName"
endpoint = "yourEndpoint"
access_key_id = "yourAccessKeyId"
access_key_secret = "yourAccessKeySecret"

[oos.AmazonS3]
bucket = "your-bucket-name"
#region = "your region"
access_key_id = "your access_key_id"
secret_access_key = "your secret_access_key"

[AI]
[AI.DeepSeek]
api_key = "your DeepSeek api key"